version: "3"
services:
  db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    env_file:
      - docker/dev/docker.env

  django:
    hostname: django
    env_file:
      - docker/dev/docker.env
    build:
      context: ./
      dockerfile: docker/dev/django/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/code

  nodejs_v1:
    hostname: nodejs_v1
    build:
      context: ./
      dockerfile: docker/dev/nodejs_v1/Dockerfile
    ports:
      - "3000:3000"
    volumes:
    - ./frontend:/code
    - /code/node_modules
